### ISSUE TITLE
Use graphql github api

### ISSUE THREAD

**Issue by craig-mulligan** [resin-io/landr#28]
https://developer.github.com/v4/guides/ 

Needs more research but should allow us to get more unauthenticated requests, as we can get all the data with one request.

**Comment by lurch** [comment]
Oooh, that looks interesting. Would that be of any use to the ProcBots framework too @hedss ?
(apologies if it's something you're already aware of / something you've already looked at)

**Comment by hedss** [comment]
It's on my radar, but I've no immediate plans to move to it (longterm, yes). There aren't any decent (from when I last looked) NPM based APIs for Github atm. The appeal of retrieving multiple sets of data in one query is extremely appealing, however.

**Comment by craig-mulligan** [comment]
Currently you have to use a gh token for every graphql request so it doesn't help me in this case, if you are going over the limits, the graphql rate limits are based on the number of resources queried, so it's hard to calculate allows more queries. However graphql api should also make things quicker because of the number of requests, but no big wins in terms of unauthenticated requests. cc @hedss.

**Comment by hedss** [comment]
@craig-mulligan Cheers Craig, that's really good to know. :+1:
