### ISSUE TITLE
Pagination on releases?

### ISSUE THREAD

**Issue by tyrantkhan** [resin-io/landr#29]
It would be nice if i could specify how many releases I want to query aka  the latest release.

edit: would be to set this up for all the fields that return a list.

**Comment by KyleAMathews** [comment]
FYI, I'm planning on adding a pagination operator to v1.

**Comment by craig-mulligan** [comment]
@tyrantkhan, so for lists we can pass a per_page parameter see here: http://mikedeboer.github.io/node-github/#api-repos-getReleases. 

The question is how we want to pass the parameter in the plugin options. 

For me makes most sense to have somthing like: 
```
{
 user: 'resin-io',
 repo: 'landr',
 releases: {
  limit: 1
 }
 commits: {
  limit: 100
 }
}
```

What do you think?
