### ISSUE TITLE
Automatically build all pages in `www/src/pages`.

### ISSUE THREAD

**Issue by craig-mulligan** [resin-io/landr#36]
Currently we only build pages that are set `gatsby-plugin-landr`, we should auto-create pages set by the user.

**Comment by KyleAMathews** [comment]
My idea for the internal page `component-page-creator` plugin was always that it should be a standalone plugin so you could set it up to auto-create pages from anywhere like you want.

Originally I wanted to ship a theme system with 1.0 and that there'd be a `gatsby-theme-core` that every site would be based on and this theme would include pre-configured plugins like the component page creator. When I realized that was going to happen I created the internal plugins idea as a work around for the lack of theme support.

Anyways, if you wanted to PR the component page creator plugin into its own plugin (while leaving it still in the internal-plugins directory), that'd work great for your use case here as well as others.

**Comment by craig-mulligan** [comment]
Yea, @KyleAMathews, Yea, I was thinking that today while working on gatsby, we should pull out the internal plugins, into their own packages. It's on my list after the current layout stuff and webpack 2 migration.

**Comment by KyleAMathews** [comment]
awesome!

Not all the internal plugins should be made external — only if a site would want to use them in different ways than core. So right now I think only the component-page-creator (which needs a better name — perhaps `gatsby-plugin-js-page-creator`) should be broken out.

I refactored the remainder of internal plugins to plugins as it was a cleaner architecture to have them rely on core APIs vs being scattered around in various places.
